local module = {
	["Chest"] = {
		["Hyperquantum Drill"] = 500;
		["Quantum Drill"] = 250;
		["Aetherborn"] = 200;
		["Impulse Driver Drill"] = 180;
		["sunny"] = 120;
		["akuma"] = 55;
		["Stormcell Drill"] = 20;
		["Surge Drill"] = 10;
		["Dusty Dana"] = 3;
		["Sandy Sarah"] = 2;
	},
	["Void Chest"] = {
		["Noli"] = 400;
		["Voidcharged Drill"] = 200;
		["Federation King"] = 180;
		["Disgraced King"] = 120;
		["Voidgate Drill"] = 55;
		["Federation Duke"] = 20;
		["Disgraced Duke"] = 10;
		["Federation Baron"] = 3;
		["Disgraced Baron"] = 2;
	},
	["Abyssal Void Chest"] = {
		["Noli Unbound"] = 400;
		["Gate To Null"] = 300;
		["Noli"] = 200;
		["Voidcharged Drill"] = 200;
		["Federation King"] = 180;
		["Disgraced King"] = 120;
		["Voidgate Drill"] = 55;
		["Federation Duke"] = 20;
		["Disgraced Duke"] = 10;
	},
	["Boundless Depths Chest"] = {
		["Noli Depthless"] = 100;
		["Quantum Void Drill"] = 25;
		["Dwarven Miner"] = 4;
		["Miner Dave"] = 2;
	},
	["Forest Chest"] = {
		["Gaia Drill"] = 100;
		["Dryad"] = 25;
		["NatureGate Drill"] = 4;
		["NatureCore Drill"] = 2;
	},
}

return module
