local module = {
	["Standard Drill"] = {
		Rarity = "Common";
		Drill = true;
		Coins = 20;
		Robux = 9;
		DevID = 3316848319;
	};
	["Reinforced Drill"] = {
		Rarity = "Common";
		Drill = true;
		Coins = 40;
		Robux = 19;
		DevID = 3316848540;
	};
	["Twin Drill"] = {
		Rarity = "Common";
		Drill = true;
		Coins = 100;
		Robux = 19;
		DevID = 3316848679;
	};
	["Compact Drill"] = {
		Rarity = "Common";
		Drill = true;
		Coins = 150;
		Robux = 19;
		DevID = 3316849107;
	};
	["Charged Drill"] = {
		Rarity = "Rare";
		Drill = true;
		Coins = 1500;
		Robux = 29;
		DevID = 3316849326;
	};
	["Surge Drill"] = {
		Rarity = "Rare";
		Drill = true;
		Coins = 4000;
		Robux = 39;
		DevID = 3316849565;
	};
	["Fusion Drill"] = {
		Rarity = "Epic";
		Drill = true;
		Coins = 25000;
		Robux = 59;
		DevID = 3316849787;
	};
	["Phase Drill"] = {
		Rarity = "Epic";
		Drill = true;
		Coins = 60000;
		Robux = 79;
		DevID = 3316850037;
	};
	["Stormcell Drill"] = {
		Rarity = "Epic";
		Drill = true;
		Coins = 120000;
		NotForSale = true;
		Robux = 699;
	};
	["KinetiCore Drill"] = {
		Rarity = "Epic";
		Drill = true;
		Coins = 120000;
		Robux = 99;
		DevID = 3316850417;
	};
	["Pulsebreaker Drill"] = {
		Rarity = "Epic";
		Drill = true;
		Coins = 120000;
		Robux = 99;
		NotForSale = true;
	};
	["Aether Drill"] = {
		Rarity = "Legendary";
		Drill = true;
		Coins = 300000;
		Robux = 299;
		DevID = 3316850820;
		MerchantPrice = 300000;
	};
	["Impulse Driver Drill"] = {
		Rarity = "Legendary";
		Drill = true;
		Coins = 300000;
		Robux = 299;
		NotForSale = true;
	};
	["Nebula Drill"] = {
		Rarity = "Mythical";
		Drill = true;
		Coins = 2000000;
		Robux = 399;
		DevID = 3316851141;
		MerchantPrice = 2000000;
	};
	["Singularity Drill"] = {
		Rarity = "Mythical";
		Drill = true;
		Coins = 4000000;
		Robux = 499;
		DevID = 3316851296;
		MerchantPrice = 4000000;
	
	};
	["Quantum Drill"] = {
		Rarity = "Mythical";
		Drill = true;
		Coins = 5000000;
		Robux = 699;
		DevID = 3316850651;
	};
	["OmniQuantum Drill"] = {
		Rarity = "Mythical";
		Drill = true;
		Coins = 10000000;
		Robux = 649;
		DevID = 3379301882;
	};
	["Arcane Drill"] = {
		Rarity = "Mythical";
		Drill = true;
		Coins = 5000000;
		NotForSale = true;
		MerchantPrice = 5000000;
		Robux = 699;
	};
	["Void Drill"] = {
		Rarity = "Mythical";
		Drill = true;
		Coins = 5000000;
		NotForSale = true;
		Robux = 699;
	};
	["HyperQuantum Drill"] = {
		Rarity = "Celestial";
		Drill = true;
		Coins = 20000000;
		Robux = 999;
		NotForSale = true;
	};
	["Eclipse Drill"] = {
		Rarity = "Celestial";
		Drill = true;
		Coins = 20000000;
		Robux = 799;
		DevID = 3316851572;
	};
	["Heavencaller Drill"] = {
		Rarity = "Celestial";
		Drill = true;
		Coins = 50000000;
		Robux = 999;
		DevID = 3379267688;
	};
	["Coral Drill"] = {
		Rarity = "Legendary";
		Coins = 120000;
		Drill = true;
		Event = true;
	};
	["Tidecaller Drill"] = {
		Rarity = "Celestial";
		Coins = 40000000;
		Drill = true;
		Event = true;
	};
	--Void Event Drills
	["Voidgate Drill"] = {
		Rarity = "Mythical";
		Drill = true;
		Coins = 5000000;
		Event = true;
	};
	["Quantum Void Drill"] = {
		Rarity = "Mythical";
		Drill = true;
		Coins = 5000000;
		Event = true;
	};
	["Voidcharged Drill"] = {
		Rarity = "Celestial";
		Drill = true;
		Coins = 20000000;
		Event = true;
	};
	["Gate To Null"] = {
		Rarity = "Celestial";
		Drill = true;
		Coins = 50000000;
		Event = true;
	};
	--Nature Event Drills
	["NatureCore Drill"] = {
		Rarity = "Epic";
		Drill = true;
		Coins = 50000;
		NatureEvent = true;
	};
	["NatureGate Drill"] = {
		Rarity = "Mythical";
		Drill = true;
		Coins = 5000000;
		NatureEvent = true;
	};
	["Gaia Drill"] = {
		Rarity = "Celestial";
		Drill = true;
		Coins = 20000000;
		NatureEvent = true;
	};
	
	["Stoneite"] = {
		Rarity = "Common";
		Drill = false;
		Ore = true;
		RNG = "1/2";
		Price = 1;
	};
	["Copper"] = {
		Rarity = "Common";
		Drill = false;
		Ore = true;
		RNG = "1/3";
		Price = 2;
	};
	["Iron"] = {
		Rarity = "Common";
		Drill = false;
		Ore = true;
		RNG = "1/5";
		Price = 3;
	};
	["Coal"] = {
		Rarity = "Common";
		Drill = false;
		Ore = true;
		RNG = "1/7";
		Price = 4;
	};
	["Tin"] = {
		Rarity = "Common";
		Drill = false;
		Ore = true;
		RNG = "1/10";
		Price = 5;
	};
	["Claystone"] = {
		Rarity = "Common";
		Drill = false;
		Ore = true;
		RNG = "1/15";
		Price = 7;
	};
	["Sandcrystal"] = {
		Rarity = "Common";
		Drill = false;
		Ore = true;
		RNG = "1/20";
		Price = 9;
	};
	["Silver"] = {
		Rarity = "Rare";
		Drill = false;
		Ore = true;
		RNG = "1/200";
		Price = 100;
	};
	["Glimmerite"] = {
		Rarity = "Rare";
		Drill = false;
		Ore = true;
		RNG = "1/500";
		Price = 300;
	};
	["Gold"] = {
		Rarity = "Rare";
		Drill = false;
		Ore = true;
		RNG = "1/800";
		Price = 500;
	};
	["Pyronite"] = {
		Rarity = "Rare";
		Drill = false;
		Ore = true;
		RNG = "1/1200";
		Price = 1000;
	};
	["Shadowite"] = {
		Rarity = "Epic";
		Drill = false;
		Ore = true;
		RNG = "1/5000";
		Price = 5000;
	};
	["Obscurite"] = {
		Rarity = "Epic";
		Drill = false;
		Ore = true;
		RNG = "1/8000";
		Price = 10000;
	};
	["Cryozite"] = {
		Rarity = "Epic";
		Drill = false;
		Ore = true;
		RNG = "1/12000";
		Price = 20000;
	};
	["Starstruck"] = {
		Rarity = "Epic";
		Drill = false;
		Ore = true;
		RNG = "1/25000";
		Price = 30000;
	};
	["Demonite"] = {
		Rarity = "Legendary";
		Drill = false;
		Ore = true;
		RNG = "1/50000";
		Price = 100000;
	};
	["Aethersteel"] = {
		Rarity = "Legendary";
		Drill = false;
		Ore = true;
		RNG = "1/100000";
		Price = 200000;
	};
	["Starcore"] = {
		Rarity = "Mythical";
		Drill = false;
		Ore = true;
		RNG = "1/1,000,000";
		Price = 1000000;
	};
	["Blue Giant"] = {
		Rarity = "Mythical";
		Drill = false;
		Ore = true;
		RNG = "1/2,500,000";
		Price = 2000000;
	};
	["Solaryte"] = {
		Rarity = "Celestial";
		Drill = false;
		Ore = true;
		RNG = "1/10000000";
		Price = 10000000;
	};
	["Eclipsium"] = {
		Rarity = "Celestial";
		Drill = false;
		Ore = true;
		RNG = "1/25000000";
		Price = 25000000;
	};
	["Starforged"] = {
		Rarity = "Celestial";
		Drill = false;
		Ore = true;
		RNG = "1/100,000,000";
		Price = 100000000;
	};
	["Voidstar"] = {
		Rarity = "Secret";
		Drill = false;
		Ore = true;
		RNG = "1/1,000,000,000";
		Price = 1000000000;
	};
	["Hellcore"] = {
		Rarity = "Secret";
		Drill = false;
		Ore = true;
		RNG = "1/10,000,000,000";
		Price = 10000000000;
	};
	["Watercrystal"] = {
		Rarity = "Common";
		Drill = false;
		Ore = true;
		RNG = "1/20";
		Price = 20;
	};
	["Miststeel"] = {
		Rarity = "Rare";
		Drill = false;
		Ore = true;
		RNG = "1/700";
		Price = 500;
	};
	["Stormvein"] = {
		Rarity = "Legendary";
		Drill = false;
		Ore = true;
		RNG = "1/75000";
		Price = 100000;
	};
	["Runeglass"] = {
		Rarity = "Common";
		Drill = false;
		Ore = true;
		RNG = "1/50";
		Price = 50;
	};
	["Atherite"] = {
		Rarity = "Rare";
		Drill = false;
		Ore = true;
		RNG = "1/555";
		Price = 400;
	};
	["Arcana"] = {
		Rarity = "Legendary";
		Drill = false;
		Ore = true;
		RNG = "1/55555";
		Price = 100000;
	};
	["Arcana Unbound"] = {
		Rarity = "Mythical";
		Drill = false;
		Ore = true;
		RNG = "1/250000";
		Price = 400000;
	};
	["Gloomstone"] = {
		Rarity = "Rare";
		Drill = false;
		Ore = true;
		RNG = "1/100";
		Price = 100;
	};
	["Dustlode"] = {
		Rarity = "Epic";
		Drill = false;
		Ore = true;
		RNG = "1/1500";
		Price = 1500;
	};
	["Abyssite"] = {
		Rarity = "Legendary";
		Drill = false;
		Ore = true;
		RNG = "1/99999";
		Price = 200000;
	};
	["Lodestar"] = {
		Rarity = "Celestial";
		Drill = false;
		Ore = true;
		RNG = "1/5,000,000";
		Price = 5000000;
	};
	["Pearl"] = {
		Rarity = "Rare";
		Drill = false;
		Ore = true;
		RNG = "1/500";
		Price = 650;
	};
	["Coral"] = {
		Rarity = "Rare";
		Drill = false;
		Ore = true;
		RNG = "1/2500";
		Price = 3000;
	};
	["Seaswept Coral"] = {
		Rarity = "Epic";
		Drill = false;
		Ore = true;
		RNG = "1/9500";
		Price = 10000;
	};
	["Pearl of the Sea"] = {
		Rarity = "Mythical";
		Drill = false;
		Ore = true;
		RNG = "1/450000";
		Price = 500000;
	};
	["Heart of the Sea"] = {
		Rarity = "Celestial";
		Drill = false;
		Ore = true;
		RNG = "1/10000000";
		Price = 10000000;
	};
	["Mossrock"] = {
		Rarity = "Rare";
		Drill = false;
		Ore = true;
		RNG = "1/250";
		Price = 250;
	};
	["Rootcrystal"] = {
		Rarity = "Epic";
		Drill = false;
		Ore = true;
		RNG = "1/2500";
		Price = 2500;
	};
	["Verdanite"] = {
		Rarity = "Legendary";
		Drill = false;
		Ore = true;
		RNG = "1/75000";
		Price = 75000;
	};
	["Gaia's Heart"] = {
		Rarity = "Celestial";
		Drill = false;
		Ore = true;
		RNG = "1/7500000";
		Price = 7500000;
	};
	["Shade Remnant"] = {
		Rarity = "Rare";
		Drill = false;
		Ore = true;
		RNG = "1/500";
		Price = 500;
	};
	["Abyssal Remnant"] = {
		Rarity = "Epic";
		Drill = false;
		Ore = true;
		RNG = "1/10000";
		Price = 10000;
	};
	
	["Summer Pack"] = {
		Rarity = "Legendary";
		Drill = false;
		Pack = true;
	};
	["Worker Contract"] = {
		Rarity = "Common";
		Pack = true;
		Drill = false;
		DiamondPrice = 9;
		MerchantPrice = 5000;
		Description = "Hire a worker to automate one of your drills. Workers increase luck, giving a better chance for rare ores.";
	};

	["Rain Totem"] = {
		Rarity = "Epic";
		Pack = true;
		Drill = false;
		DiamondPrice = 49;
		MerchantPrice = 100000;
		Description = "Summon a temporary rainstorm, adding new ores to the loot pool for 5 minutes.";
	};

	["Arcane Totem"] = {
		Rarity = "Legendary";
		Pack = true;  
		Drill = false;
		DiamondPrice = 99;
		MerchantPrice = 250000;
		Description = "Summons mystical arcane weather, adding new ores to the loot pool for 5 minutes.";
	};
	
	["Nature Totem"] = {
		Rarity = "Legendary";
		Pack = true;  
		Drill = false;
		DiamondPrice = 249;
		MerchantPrice = 250000;
		Description = "Summons mystical nature weather, adding new ores to the loot pool for 5 minutes.";
	};

	["Void Totem"] = {
		Rarity = "Legendary";
		Pack = true;
		Drill = false;
		DiamondPrice = 249;
		MerchantPrice = 500000;
		Description = "Unleashes a voidstorm, adding new ores to the loot pool for 5 minutes.";
	};

	["Simple Luck Potion"] = {
		Rarity = "Epic";
		Pack = true;
		Drill = false;
		DiamondPrice = 99;
		MerchantPrice = 100000;
		Description = "Temporarily increases your personal luck by 50% for 5 minutes.";
	};

	["Advanced Luck Potion"] = {
		Rarity = "Legendary";
		Pack = true;
		Drill = false;
		DiamondPrice = 149;
		MerchantPrice = 250000;
		Description = "Temporarily increases your personal luck by 100% for 5 minutes.";
	};

	["Mythical Luck Potion"] = {
		Rarity = "Mythical";
		Pack = true;
		Drill = false;
		DiamondPrice = 249;
		MerchantPrice = 500000;
		Description = "Greatly boosts your personal luck by 300% for 5 minutes. Ideal for legendary ore hunting.";
	};
	
	["Player Contract"] = {
		Rarity = "Epic";
		Pack = true;
		Drill = false;
		MerchantPrice = 10000;
		Description = "Gives you a worker based on players that helped Drill It!";
	};
	["Chest"] = {
		Rarity = "Rare";
		Pack = true;
		DiamondPrice = 99;
		Drill = false;
		Description = "Contains rare loot!";
	};
	["Void Chest"] = {
		Rarity = "Epic";
		Pack = true;
		VoidDiamondPrice = 49;
		Drill = false;
		Description = "Contains limited time loot from the void event!";
	};
	["Abyssal Void Chest"] = {
		Rarity = "Legendary";
		Pack = true;
		VoidDiamondPrice = 249;
		Drill = false;
		Description = "Contains deluxe limited time loot from the void event!";
	};
	["Boundless Depths Chest"] = {
		Rarity = "Mythical";
		Pack = true;
		VoidDiamondPrice = 249;
		Drill = false;
		Description = "Contains deluxe limited time loot from the void event!";
	};
	["Forest Chest"] = {
		Rarity = "Mythical";
		Pack = true;
		Drill = false;
		NatureEvent = true;
		Description = "Contains deluxe limited time loot from the void event!";
	};
	
	["Pickaxe"] = {
		Rarity = "Common";
		Pack = true;
		Drill = false;
		Description = "Used to mine ores in the void event!";
	};
	["Dwarven Pickaxe"] = {
		Rarity = "Epic";
		Pack = true;
		Drill = false;
		Description = "Used to mine ores in the void event!";
	};
	["Reality Crusher"] = {
		Rarity = "Celestial";
		Pack = true;
		Drill = false;
		Description = "Used to mine ores in the void event!";
	};
}

return module
